### ISSUE TITLE
Create a header to verify API calls do not exceed the call limit

### ISSUE THREAD

**Issue by EvanaHolevas** [CSCI-152/Meal-Planner#7]

**Comment by EvanaHolevas** [comment]
Overage can be avoided by monitoring the response header:

X-Ratelimit-Classifications-Limit: X
X-Ratelimit-Classifications-Remaining: X
X-Ratelimit-Requests-Limit: X
X-Ratelimit-Requests-Remaining: X
X-Ratelimit-Tinyrequests-Limit: X
X-Ratelimit-Tinyrequests-Remaining: X

**Comment by biyori** [comment]
Added to master
